################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.md", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Development Status :: 5 - Production/Stable",
		"License :: OSI Approved :: Apache Software License",
	],
	description = "This python module provides a mixin for dumping objects.",
	download_url = "https://github.com/jkpubsrc/python-module-jk-prettyprintobj/tarball/0.2020.10.11",
	include_package_data = False,
	install_requires = [
	],
	keywords = [
		"pretty-print",
		"debugging",
		"debug"
	],
	license = "Apache 2.0",
	name = "jk_prettyprintobj",
	packages = [
		"jk_prettyprintobj",
	],
	url = "https://github.com/jkpubsrc/python-module-jk-prettyprintobj",
	version = "0.2020.10.11",
	zip_safe = False,
	long_description = readme(),
	long_description_content_type="text/markdown",
)
